name: 'produce trash 🗑️'

# Run every hour on the hour
on:
  schedule:
    - cron: '51 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
          persist-credentials: false
          fetch-depth: 0
      - name: 'Set up Node'
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: 'Make trash commits'
        run: |
          git config --local user.email "aleksijaakkojuhani@gmail.com"
          git config --local user.name "Aleksi Peltola"
          node makeCommits.js
      - name: 'Push changes'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.TOKEN }}
          force: 'true'
          branch: 'master'
